(define (proc-definition? xs)
  (if (list? xs)
      (if (equal? (car xs) 'lambda)
          (equal? (car xs) 'lambda)
          (if (equal? (car xs) 'define)
              (if (or (list? (cadr xs)) (pair? (cadr xs)))
                  (or (list? (cadr xs)) (pair? (cadr xs)))
                  (proc-definition? (caddr xs)))
              (equal? (car xs) 'define)))
      (list? xs)))